version: 1
disable_existing_loggers: false
formatters:
  default:
    format: "%(asctime)s | %(levelname)-8s | %(name)s:%(lineno)d | %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S%z"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stderr
  file:
    class: logging.FileHandler
    level: INFO
    formatter: default
    filename: app.log
    encoding: utf-8
root:
  level: INFO
  handlers: ["console"] 